### ISSUE TITLE
gDoc & PDF version of assembly instructions

### ISSUE THREAD

**Issue by claymccauley** [SkydivinGirl/SaV64#1]
Thank you so much for making your project open source!  I was gathering the resources to build this and noticed the docx file points to images on a site that seems to no longer exist.  I imported into gDocs and added all the images back from your images folder on GitHub and also created a PDF version from that.  I've shared both from my Google Drive account.  If you'd like to add either version the links are included below.

PDF version:
https://drive.google.com/file/d/1Y8o3M_jWW-OstkogqZBjHKQuKZh7ea6G/view?usp=sharing

Editable gDoc:
https://docs.google.com/document/d/1DCR5AHeO0SbhK5fa8YSOOx2IC-TLvfHvv1ucUbhZ1Ro/edit?usp=sharing

**Comment by SkydivinGirl** [comment]
Thanks Clay!  I've added the PDF to the Documentation folder of the project. :)
